name: action
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Git
      run: |
        git config --global user.name '${{ secrets.GIT_USER_NAME }}'
        git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
    - name: Upgrade Pip
      run: pip install --upgrade pip
    - name: Install Unity Version Manager
      run: pip install uvm
    - name: Clone Repository
      run: git clone ${{ secrets.REPOSITORY_URL }}
    - name: Set Version
      run: |
        cd ${{ secrets.REPOSITORY_NAME }}
        uvm build setup "./ProjectSettings/ProjectSettings.asset"
    - name: Commit Changes
      run: |
        cd ${{ secrets.REPOSITORY_NAME }}
        git add "./ProjectSettings/ProjectSettings.asset"
        git commit --allow-empty -m "Set Version"
        git push
